name: Package Project

# Controls when the workflow will run
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # get the code under $GITHUB_WORKSPACE directory
      - uses: actions/checkout@v2
      # get the python
      - name: Set up Python3
        uses: actions/setup-python@v3
      - name: Install deps
        run: make deps
      - name: Lint
        run: make lint
      - name: Test
        run: make test
